version: "3.7"
services:
  jenkins:
    image: benkorichard/jenkins-dind:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy: 
        condition: any
    ports:
      - 8080:8080
    volumes:
    # Change host directory when using docker-machine
      - /vagrant/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JAVA_OPTS: "-Djava.util.logging.config.file=/var/jenkins_home/log.properties"
    networks: 
      - jenkins


networks:
  jenkins:
    external: true
